package com.itpdf.app.domain.model

import java.text.DecimalFormat
import java.time.Instant
import java.time.LocalDate
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.util.Locale
import kotlin.math.log10
import kotlin.math.pow

/**
 * Domain model representing a PDF document entity.
 * This class encapsulates metadata for PDF files stored locally or generated by the app.
 * Refined for performance and accurate date handling using java.time (API 26+).
 *
 * @property id Unique identifier for the document.
 * @property name The display name of the PDF file.
 * @property path The absolute file system path where the PDF is stored.
 * @property sizeInBytes The file size in bytes.
 * @property createdAt The timestamp (epoch milliseconds) of creation.
 */
data class PdfDocument(
    val id: String,
    val name: String,
    val path: String,
    val sizeInBytes: Long,
    val createdAt: Long
) {
    /**
     * Converts the raw byte size into a human-readable string.
     * Uses coercion to prevent array index out of bounds for extremely large values.
     */
    val formattedSize: String
        get() {
            if (sizeInBytes <= 0) return "0 B"
            val units = arrayOf("B", "KB", "MB", "GB", "TB")
            val digitGroups = (log10(sizeInBytes.toDouble()) / log10(1024.0))
                .toInt()
                .coerceIn(0, units.lastIndex)
            
            return try {
                val value = sizeInBytes / 1024.0.pow(digitGroups.toDouble())
                DecimalFormat("#,##0.#").format(value) + " " + units[digitGroups]
            } catch (e: Exception) {
                "Unknown Size"
            }
        }

    /**
     * Formats the creation timestamp using java.time for regional accuracy.
     * Logic: Shows time if the document was created today, otherwise shows date.
     */
    val formattedDate: String
        get() {
            return try {
                val zoneId = ZoneId.systemDefault()
                val documentDateTime = Instant.ofEpochMilli(createdAt).atZone(zoneId)
                val documentDate = documentDateTime.toLocalDate()
                val today = LocalDate.now(zoneId)

                val pattern = if (documentDate.isEqual(today)) {
                    "hh:mm a"
                } else {
                    "dd MMM yyyy"
                }
                documentDateTime.format(DateTimeFormatter.ofPattern(pattern, Locale.getDefault()))
            } catch (e: Exception) {
                "Unknown Date"
            }
        }

    /**
     * Returns the file extension in lowercase.
     */
    fun getExtension(): String = name.substringAfterLast('.', "pdf").lowercase()
}